### ISSUE TITLE
Implementation Kanban board

### ISSUE THREAD

**Issue by mgmediaweb** [mgmediaweb/js-group-capstone-project#21]
Today we created a group repository and install the kanban, we clone the tasks from the Microverse Template.

Send the issue for the Code Review check.

Link of the board:
https://github.com/mgmediaweb/js-group-capstone-project/projects/2

**Comment by OmarRamoun** [comment]
# 🟢 Project Approved! 🏆

## Hi @mgmediaweb and @Draxeytina 👋

Your project is complete! ✔️ 🏁

Congratulations! 🎉.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
